version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    restart: unless-stopped
    ports:
      - 3000
    command: rails new --api . && rails s -b 0.0.0.0
    volumes:
      - .:/app
    # environment:
    #   APP_MAILER_FROM: ${APP_MAILER_FROM}
    #   APP_MAILER_SMTP_ADDRESS: ${APP_MAILER_SMTP_ADDRESS}
  # mongo:
  #   image: mongo:latest
  #   restart: unless-stopped
  #   ports:
  #     - 27017
  # redis:
  #   image: redis:latest
  #   restart: unless-stopped
  #   ports:
  #     - 6379
