version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    restart: unless-stopped
    ports:
      - 3000
    volumes:
      - .:/app
    # environment: {}
  # mariadb:
  #   image: mariadb:latest
  #   restart: unless-stopped
  #   ports:
  #     - 3306
  # redis:
  #   image: redis:latest
  #   restart: unless-stopped
  #   ports:
  #     - 6379
